---
group: webapps
user: userapps
home: /webapps
path_venv: "/opt/venv" # Recuerda modificar travis si cambias este valor

# Estas contraseñas deben coincidir con las postgres
database_name: scrapers
database_user: userdb
database_password: password
database_host: db
database_port: 5432

# Configuraciones AIRFLOW
host_airflow: http://backend:8080
web_server_host: backend
web_server_port: 8080
redis: redis://redis:6379
flower_host: backend
flower_port: 5555
queue_names:
  - scrapers
  - chore

# ADMIN User django
django_user: admin
django_email: admin@admin.com
django_password: admin
django_settings: config.settings.local

# SUPERVISOR config
web_socket: tcp://0.0.0.0:8003

# NGINX config
server_name: localhost 127.0.0.1 0.0.0.0
origin: http://localhost:8003

os_environment:
  - key: SECRET_KEY
    value: "uawjn2ct=00pg)k#1$yu0h*6q*zkr-mq8t9$n__^)l1qpl=oj&"
  - key: ENV
    value: local
